In [9]:
import pandas as pd
import numpy as np
df = pd.read_csv("student_1.csv")
print(df.head())
print("\n\n")

print(df.dropna(axis=0))


print(df.fillna(0))
print(df['gender'].fillna('No Gender'))
print(df['FDS'].fillna(df['FDS'].mean()))
print(df['ML'].fillna(df['ML'].mean()))
print(df['AI'].fillna(df['AI'].mean()))
print(df['P_S'].fillna(df['P_S'].mean()))
print(df['DMBI'].fillna(df['DMBI'].mean()))

  Student_name Gender Enrollment No.   FDS    ML    AI   P_S  DMBI  \
0      Parth        M    ET21BTAI001  89.0  90.0  78.0  80.0  75.0
1      Aryan C      M    ET21BTAI002  75.0  78.0  75.0  91.0  90.0
2        Rohit      M    ET21BTAI003  89.0  90.0  85.0  82.0  78.0
3      Prayesh      M    ET21BTAI004  89.0  90.0  87.0  81.0  78.0
4        Urvil      M    ET21BTAI005  75.0  78.0  75.0  78.0  87.0

   Mobile No.     City  sem1  sem2  sem3  sem4  sem5
0  9984364546    Surat  89.0  90.0  78.0  80.0  75.0
1  9856372889  Vadodra  75.0  78.0  75.0  91.0  90.0
2  9843647464    Surat  89.0  90.0  85.0  82.0  78.0
3  9313980494    Surat  89.0  90.0  87.0  81.0  78.0
4  9857372904  Vadodra  75.0  78.0  75.0  78.0  87.0



   Student_name Gender Enrollment No.        FDS         ML         AI  \
0       Parth        M    ET21BTAI001  89.000000  90.000000  78.000000
1       Aryan C      M    ET21BTAI002  75.000000  78.000000  75.000000
2         Rohit      M    ET21BTAI003  89.000000  90.000000  85.000000
3       Prayesh      M    ET21BTAI004  89.000000  90.000000  87.000000
4         Urvil      M    ET21BTAI005  75.000000  78.000000  75.000000
5       Parthiv      M    ET21BTAI006  95.000000  94.000000  90.000000
6          Smit      M    ET21BTAI007  88.333333  88.666667  87.866667
7         Manav      M    ET21BTAI008  89.190476  89.238095  89.638095
8         Tisha      F    ET21BTAI009  90.047619  89.809524  91.409524
9        Khushi      F    ET21BTAI010  90.904762  90.380952  93.180952
10    Priyanshi      F    ET21BTAI011  91.761905  90.952381  94.952381
11      Ridhdhi      F    ET21BTAI012  92.619048  91.523810  96.723810
12       Riyank      M    ET21BTAI013  93.476190  92.095238  98.495238
13        Hasti      F    ET21BTAI014  94.333333  92.666667  67.000000
14         Mili      F    ET21BTAI015  95.190476  93.238095  78.000000
15     Parthish      M    ET21BTAI016  96.047619  93.809524  89.000000
16      Tanisha      F    ET21BTAI017  96.904762  94.380952  76.000000
17        Disha      F    ET21BTAI018  97.761905  94.952381  78.000000
18       Niyati      F    ET21BTAI019  98.619048  95.523810  67.000000

          P_S       DMBI   Mobile No.     City       sem1       sem2  \
0   80.000000  75.000000   9984364546    Surat  89.000000  90.000000
1   91.000000  90.000000   9856372889  Vadodra  75.000000  78.000000
2   82.000000  78.000000   9843647464    Surat  89.000000  90.000000
3   81.000000  78.000000   9313980494    Surat  89.000000  90.000000
4   78.000000  87.000000   9857372904  Vadodra  75.000000  78.000000
5   98.000000  95.000000   4532612345   Canada  95.000000  94.000000
6   90.000000  92.933333   4355656455    Surat  88.333333  88.666667
7   91.428571  95.533333  56676676767  Vadodra  89.190476  89.238095
8   92.857143  98.133333  65654665445    Surat  90.047619  89.809524
9   94.285714  67.000000   5656546556    Surat  90.904762  90.380952
10  95.714286  78.000000   5656776776  Vadodra  91.761905  90.952381
11  97.142857  67.000000   8975487334   Canada  92.619048  91.523810
12  98.571429  78.000000  56767655656    Surat  93.476190  92.095238
13  78.000000  87.000000  67786756455  Vadodra  94.333333  92.666667
14  98.000000  67.000000   6767675656    Surat  95.190476  93.238095
15  78.000000  65.000000    343445324    Surat  96.047619  93.809524
16  76.000000  76.000000   3245342354  Vadodra  96.904762  94.380952
17  68.000000  75.000000   7686575656   Canada  97.761905  94.952381
18  86.000000  78.000000   6745656455    Surat  98.619048  95.523810

         sem3       sem4       sem5
0   78.000000  80.000000  75.000000
1   75.000000  91.000000  90.000000
2   85.000000  82.000000  78.000000
3   87.000000  81.000000  78.000000
4   75.000000  78.000000  87.000000
5   90.000000  98.000000  95.000000
6   87.866667  90.000000  92.933333
7   89.638095  91.428571  95.533333
8   91.409524  92.857143  98.133333
9   93.180952  94.285714  67.000000
10  94.952381  95.714286  78.000000
11  96.723810  97.142857  67.000000
12  98.495238  98.571429  78.000000
13  67.000000  78.000000  87.000000
14  78.000000  98.000000  67.000000
15  89.000000  78.000000  65.000000
16  76.000000  76.000000  76.000000
17  78.000000  68.000000  75.000000
18  67.000000  86.000000  78.000000
   Student_name Gender Enrollment No.        FDS         ML         AI  \
0       Parth        M    ET21BTAI001  89.000000  90.000000  78.000000
1       Aryan C      M    ET21BTAI002  75.000000  78.000000  75.000000
2         Rohit      M    ET21BTAI003  89.000000  90.000000  85.000000
3       Prayesh      M    ET21BTAI004  89.000000  90.000000  87.000000
4         Urvil      M    ET21BTAI005  75.000000  78.000000  75.000000
5       Parthiv      M    ET21BTAI006  95.000000  94.000000  90.000000
6          Smit      M    ET21BTAI007  88.333333  88.666667  87.866667
7         Manav      M    ET21BTAI008  89.190476  89.238095  89.638095
8         Tisha      F    ET21BTAI009  90.047619  89.809524  91.409524
9        Khushi      F    ET21BTAI010  90.904762  90.380952  93.180952
10    Priyanshi      F    ET21BTAI011  91.761905  90.952381  94.952381
11      Ridhdhi      F    ET21BTAI012  92.619048  91.523810  96.723810
12       Riyank      M    ET21BTAI013  93.476190  92.095238  98.495238
13        Hasti      F    ET21BTAI014  94.333333  92.666667  67.000000
14         Mili      F    ET21BTAI015  95.190476  93.238095  78.000000
15     Parthish      M    ET21BTAI016  96.047619  93.809524  89.000000
16      Tanisha      F    ET21BTAI017  96.904762  94.380952  76.000000
17        Disha      F    ET21BTAI018  97.761905  94.952381  78.000000
18       Niyati      F    ET21BTAI019  98.619048  95.523810  67.000000

          P_S       DMBI   Mobile No.     City       sem1       sem2  \
0   80.000000  75.000000   9984364546    Surat  89.000000  90.000000
1   91.000000  90.000000   9856372889  Vadodra  75.000000  78.000000
2   82.000000  78.000000   9843647464    Surat  89.000000  90.000000
3   81.000000  78.000000   9313980494    Surat  89.000000  90.000000
4   78.000000  87.000000   9857372904  Vadodra  75.000000  78.000000
5   98.000000  95.000000   4532612345   Canada  95.000000  94.000000
6   90.000000  92.933333   4355656455    Surat  88.333333  88.666667
7   91.428571  95.533333  56676676767  Vadodra  89.190476  89.238095
8   92.857143  98.133333  65654665445    Surat  90.047619  89.809524
9   94.285714  67.000000   5656546556    Surat  90.904762  90.380952
10  95.714286  78.000000   5656776776  Vadodra  91.761905  90.952381
11  97.142857  67.000000   8975487334   Canada  92.619048  91.523810
12  98.571429  78.000000  56767655656    Surat  93.476190  92.095238
13  78.000000  87.000000  67786756455  Vadodra  94.333333  92.666667
14  98.000000  67.000000   6767675656    Surat  95.190476  93.238095
15  78.000000  65.000000    343445324    Surat  96.047619  93.809524
16  76.000000  76.000000   3245342354  Vadodra  96.904762  94.380952
17  68.000000  75.000000   7686575656   Canada  97.761905  94.952381
18  86.000000  78.000000   6745656455    Surat  98.619048  95.523810

         sem3       sem4       sem5
0   78.000000  80.000000  75.000000
1   75.000000  91.000000  90.000000
2   85.000000  82.000000  78.000000
3   87.000000  81.000000  78.000000
4   75.000000  78.000000  87.000000
5   90.000000  98.000000  95.000000
6   87.866667  90.000000  92.933333
7   89.638095  91.428571  95.533333
8   91.409524  92.857143  98.133333
9   93.180952  94.285714  67.000000
10  94.952381  95.714286  78.000000
11  96.723810  97.142857  67.000000
12  98.495238  98.571429  78.000000
13  67.000000  78.000000  87.000000
14  78.000000  98.000000  67.000000
15  89.000000  78.000000  65.000000
16  76.000000  76.000000  76.000000
17  78.000000  68.000000  75.000000
18  67.000000  86.000000  78.000000

KeyError: 'gender'